Merge more changes to fix build error
  CC      drivers/huawei_platform/touchscreen/focaltech_8736/focaltech_flash.o
../../../../../../kernel/huawei/msm8953/drivers/huawei_platform/touchscreen/focaltech_8736/focaltech_flash.c: In function 'fts_ctpm_auto_upgrade':
../../../../../../kernel/huawei/msm8953/drivers/huawei_platform/touchscreen/focaltech_8736/focaltech_flash.c:3971:2: error: implicit declaration of function 'app_info_set' [-Werror=implicit-function-declaration]
  err = app_info_set("touch_panel", AppInfoBuf);
  ^
cc1: some warnings being treated as errors
make[6]: *** [drivers/huawei_platform/touchscreen/focaltech_8736/focaltech_flash.o] Error 1
make[5]: *** [drivers/huawei_platform/touchscreen/focaltech_8736] Error 2