qpnp-smbcharger.c: remove duplicate to fix build error
* Caused by merging.

  CC      drivers/power/qpnp-smbcharger.o
../../../../../../kernel/huawei/msm8953/drivers/power/qpnp-smbcharger.c: In function 'smbchg_battery_get_property':
../../../../../../kernel/huawei/msm8953/drivers/power/qpnp-smbcharger.c:6405:2: error: duplicate case value
  case POWER_SUPPLY_PROP_CHARGE_FULL:
  ^
../../../../../../kernel/huawei/msm8953/drivers/power/qpnp-smbcharger.c:6366:2: error: previously used here
  case POWER_SUPPLY_PROP_CHARGE_FULL:
  ^
make[4]: *** [drivers/power/qpnp-smbcharger.o] Error 1