isp/msm_isp_stats_util.c: revert some changes to fix build error
  CC      drivers/media/platform/msm/camera_v2/isp/msm_isp_stats_util.o
../../../../../../kernel/huawei/msm8953/drivers/media/platform/msm/camera_v2/isp/msm_isp_stats_util.c: In function 'msm_isp_start_stats_stream':
../../../../../../kernel/huawei/msm8953/drivers/media/platform/msm/camera_v2/isp/msm_isp_stats_util.c:734:3: error: implicit declaration of function 'ISP_HW_DBG' [-Werror=implicit-function-declaration]
   ISP_HW_DBG("%s: stats_mask %x %x active streams %d\n",
   ^
cc1: some warnings being treated as errors